export interface SectionMeta {
  id: string;
  title: string;
  short: string;
  blurb: string;
  icon: string;
  /** Interview weight used for prioritisation badges on the dashboard. */
  priority: 'Critical' | 'High' | 'Medium';
  group: string;
  hue: number;
}

export const SECTION_GROUPS = [
  'Coding & Problem Solving',
  'Design',
  'Platform & Data',
  'Language & Frameworks',
  'Engineering Craft',
  'The Human Round',
  'Interview Craft',
] as const;

export const SECTIONS: SectionMeta[] = [
  {
    id: 'dsa',
    title: 'Data Structures & Algorithms',
    short: 'DSA',
    blurb: 'Every structure, pattern and algorithm that shows up in a coding round — with the recognition cues that tell you which one to reach for.',
    icon: 'binary',
    priority: 'Critical',
    group: 'Coding & Problem Solving',
    hue: 258,
  },
  {
    id: 'system-design',
    title: 'System Design & Distributed Systems',
    short: 'System Design',
    blurb: 'Building blocks, distributed-systems theory, reliability and scalability — the vocabulary and trade-offs of an HLD round.',
    icon: 'network',
    priority: 'Critical',
    group: 'Design',
    hue: 199,
  },
  {
    id: 'hld-problems',
    title: 'System Design Case Studies',
    short: 'HLD Practice',
    blurb: 'Fifteen designs worked end-to-end: requirements, estimates, API, data model, architecture, bottlenecks and deep dives.',
    icon: 'blueprint',
    priority: 'Critical',
    group: 'Design',
    hue: 187,
  },
  {
    id: 'lld',
    title: 'Low Level Design & OOD',
    short: 'LLD',
    blurb: 'OOP, SOLID, UML and the design patterns that actually appear in interviews — plus how to structure a 45-minute LLD round.',
    icon: 'cube',
    priority: 'High',
    group: 'Design',
    hue: 32,
  },
  {
    id: 'lld-problems',
    title: 'LLD Case Studies',
    short: 'LLD Practice',
    blurb: 'Classic machine-coding problems solved with clean class models, C# code, thread-safety notes and extension points.',
    icon: 'puzzle',
    priority: 'High',
    group: 'Design',
    hue: 18,
  },
  {
    id: 'java',
    title: 'Java & the JVM',
    short: 'Java',
    blurb: 'Language semantics, collections, streams, concurrency and JVM internals at the depth a senior Java interview probes.',
    icon: 'java',
    priority: 'Critical',
    group: 'Language & Frameworks',
    hue: 8,
  },
  {
    id: 'spring-boot',
    title: 'Spring & Spring Boot',
    short: 'Spring Boot',
    blurb: 'Dependency injection, the MVC and WebFlux stacks, Spring Data and transactions, security, testing and production hardening.',
    icon: 'spring',
    priority: 'Critical',
    group: 'Language & Frameworks',
    hue: 105,
  },
  {
    id: 'csharp-dotnet',
    title: 'C# & .NET',
    short: 'C# / .NET',
    blurb: 'Language semantics, memory, async, concurrency and CLR internals at the depth a senior .NET interview probes.',
    icon: 'dotnet',
    priority: 'Critical',
    group: 'Language & Frameworks',
    hue: 271,
  },
  {
    id: 'backend',
    title: 'APIs & ASP.NET Core',
    short: 'Backend',
    blurb: 'REST done properly, the ASP.NET Core pipeline, and the production concerns that separate a toy API from a real one.',
    icon: 'server',
    priority: 'Critical',
    group: 'Language & Frameworks',
    hue: 210,
  },
  {
    id: 'databases',
    title: 'Databases, SQL & Redis',
    short: 'Databases',
    blurb: 'Query craft, indexes, execution plans, transactions and isolation — then NoSQL modelling and Redis in anger.',
    icon: 'database',
    priority: 'High',
    group: 'Platform & Data',
    hue: 150,
  },
  {
    id: 'azure',
    title: 'Azure Cloud',
    short: 'Azure',
    blurb: 'Networking, identity, compute, messaging and data services — with a deep dive on Cosmos DB that interviewers love.',
    icon: 'cloud',
    priority: 'Critical',
    group: 'Platform & Data',
    hue: 205,
  },
  {
    id: 'messaging',
    title: 'Messaging & Event-Driven',
    short: 'Messaging',
    blurb: 'Delivery semantics, idempotency, ordering, retries, DLQs, outbox and saga — the hardest questions in async systems.',
    icon: 'queue',
    priority: 'High',
    group: 'Platform & Data',
    hue: 287,
  },
  {
    id: 'ai-engineering',
    title: 'AI & GenAI Engineering',
    short: 'AI Engineering',
    blurb: 'LLM mechanics, RAG, embeddings, agents, MCP and AI system design — the fastest-growing interview surface.',
    icon: 'sparkles',
    priority: 'High',
    group: 'Platform & Data',
    hue: 322,
  },
  {
    id: 'frontend',
    title: 'JavaScript, TypeScript & React',
    short: 'Frontend',
    blurb: 'Enough front-end depth to hold a full-stack conversation: closures, the event loop, hooks, rendering and performance.',
    icon: 'browser',
    priority: 'Medium',
    group: 'Language & Frameworks',
    hue: 47,
  },
  {
    id: 'languages',
    title: 'Language Breadth',
    short: 'Languages',
    blurb: 'Python, C++ and Node.js at the depth a polyglot interview probes — enough to hold a credible conversation outside your primary stack.',
    icon: 'code',
    priority: 'Medium',
    group: 'Language & Frameworks',
    hue: 88,
  },
  {
    id: 'security',
    title: 'Security',
    short: 'Security',
    blurb: 'AuthN vs AuthZ, OAuth 2.0, JWT, OWASP risks, cloud least-privilege and vulnerability management.',
    icon: 'shield',
    priority: 'Medium',
    group: 'Engineering Craft',
    hue: 0,
  },
  {
    id: 'devops',
    title: 'Docker, Kubernetes & DevOps',
    short: 'DevOps',
    blurb: 'Containers, orchestration, deployment strategies, CI/CD design and infrastructure as code with Terraform.',
    icon: 'container',
    priority: 'Medium',
    group: 'Engineering Craft',
    hue: 195,
  },
  {
    id: 'observability',
    title: 'Observability & Production',
    short: 'Observability',
    blurb: 'Logs, metrics, traces, SLOs and incident response — the material behind "prod latency just spiked, what do you do?"',
    icon: 'pulse',
    priority: 'High',
    group: 'Engineering Craft',
    hue: 95,
  },
  {
    id: 'testing',
    title: 'Testing',
    short: 'Testing',
    blurb: 'The test pyramid, doubles, integration and contract testing, load and chaos testing, and testing in .NET.',
    icon: 'check',
    priority: 'Medium',
    group: 'Engineering Craft',
    hue: 165,
  },
  {
    id: 'fundamentals',
    title: 'CS & Engineering Fundamentals',
    short: 'Fundamentals',
    blurb: 'Clean code, Git, compatibility and migrations, plus OS, memory and networking fundamentals that still get asked.',
    icon: 'book',
    priority: 'Medium',
    group: 'Engineering Craft',
    hue: 225,
  },
  {
    id: 'behavioural',
    title: 'Behavioural & Leadership',
    short: 'Behavioural',
    blurb: 'A STAR story bank, leadership and conflict narratives, the hiring-manager round and company-specific prep.',
    icon: 'users',
    priority: 'High',
    group: 'The Human Round',
    hue: 340,
  },
  {
    id: 'resume',
    title: 'Resume Deep Dive',
    short: 'Resume',
    blurb: 'Turn every résumé bullet into a defensible architecture story, with numbers, trade-offs and failure drills.',
    icon: 'file',
    priority: 'Critical',
    group: 'The Human Round',
    hue: 262,
  },
  {
    id: 'interview-process',
    title: 'The Interview Loop',
    short: 'Interview Craft',
    blurb: 'How the loop is actually structured and scored — round-by-round tactics, machine-coding rounds, revision plans and the night-before one-pagers.',
    icon: 'compass',
    priority: 'High',
    group: 'Interview Craft',
    hue: 44,
  },
];

export const SECTION_MAP: Record<string, SectionMeta> = Object.fromEntries(
  SECTIONS.map((s) => [s.id, s]),
);

export function getSection(id: string): SectionMeta {
  return (
    SECTION_MAP[id] ?? {
      id,
      title: id,
      short: id,
      blurb: '',
      icon: 'book',
      priority: 'Medium',
      group: 'Engineering Craft',
      hue: 220,
    }
  );
}
